export const products = [
  { "categID" : 1,
    "prodID" : 1,
    "name" : "Spiky Ball",
    "description" : "Toy",
    "price" : "$5",
    "image" : "/images/spiky ball.jpg"},

  { "categID" : 1,
    "prodID" : 2,
    "name" : "Orthopedic Cuddler",
    "description" : "Dog bed",
    "price" : "$30",
    "image" : "/images/orthopedic cuddler.jpg"},

  { "categID" : 1,
    "prodID" : 3,
    "name" : "Stainless Steel Bowl",
    "description" : "Water bowl",
    "price" : "$10", 
    "image" : "/images/water bowl.jpg"},

  { "categID" : 1,
    "prodID" : 4, 
    "name" : "Treat Pouch",
    "description": "Bag for treats",
    "price": "$8",
    "image": "/images/treat pouch.jpg"},

  { "categID" : 2,
    "prodID" : 5,
    "name" : "Yarn Ball",
    "description" : "Toy",
    "price" : "$5",
    "image" : "/images/yarn ball.jpg"},

  { "categID" : 2,
    "prodID" : 6,
    "name" : "Playbox",
    "description" : "Cat playbox",
    "price" : "$50",
    "image" : "/images/cat playbox.jpg"},

  { "categID" : 2,
    "prodID" : 7, 
    "name" : "Lounger",
    "description" : "Cat bed",
    "price" : "$20", 
    "image" : "/images/cat bed.jpg"},

  { "categID" : 2,
    "prodID" : 8,
    "name" : "Feeder",
    "description": "Food dispenser",
    "price": "$35",
    "image": "/images/cat feeder.jpg"},

  { "categID" : 3,
    "prodID" : 9,
    "name" : "Aquarium",
    "description" : "Fish Tank",
    "price" : "$35",
    "image" : "/images/fish tank.jpg"},

  { "categID" : 3,
    "prodID" : 10,
    "name" : "Barrel Ornament",
    "description" : "Aquarium decoration",
    "price" : "$5",
    "image" : "/images/decor barrel.jpg"},

  { "categID" : 3,
    "prodID" : 11,
    "name" : "Driftwood Ornament",
    "description" : "Aquarium decoration",
    "price" : "$10", 
    "image" : "/images/decor tree.jpg"}  
]